// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220118092335_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("BLL.Data.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("BLL.Data.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CaseClosed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("BLL.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aacfeb4f-4d22-45f9-a396-e9720ce66b17"),
                            CreatedAt = new DateTime(2022, 1, 18, 9, 23, 35, 831, DateTimeKind.Utc).AddTicks(1484),
                            Email = "admin@support.org",
                            Password = "7Tl+1DbEbv3Nrn78ExihNJtFQeJ9Ab31H53Ag/O3F8I=",
                            UpdatedAt = new DateTime(2022, 1, 18, 9, 23, 35, 831, DateTimeKind.Utc).AddTicks(1486),
                            UserType = 2,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("1547ef23-8228-4ca9-8933-60556ff711d5"),
                            CreatedAt = new DateTime(2022, 1, 18, 9, 23, 35, 831, DateTimeKind.Utc).AddTicks(1682),
                            Email = "userone@support.org",
                            Password = "DeLz1xxToYk9dnASFiKlbN5XxMgRmsL2yMA0bOO9bFs=",
                            UpdatedAt = new DateTime(2022, 1, 18, 9, 23, 35, 831, DateTimeKind.Utc).AddTicks(1682),
                            UserType = 2,
                            Username = "userone"
                        },
                        new
                        {
                            Id = new Guid("07d44841-3ee6-4a23-b961-8f7d34b34e3e"),
                            CreatedAt = new DateTime(2022, 1, 18, 9, 23, 35, 831, DateTimeKind.Utc).AddTicks(1716),
                            Email = "usertwo@support.org",
                            Password = "dgs7m+tZqBY8cY/fHUnddJ840YgROAQFQEnHUDMV1Q0=",
                            UpdatedAt = new DateTime(2022, 1, 18, 9, 23, 35, 831, DateTimeKind.Utc).AddTicks(1716),
                            UserType = 2,
                            Username = "usertwo"
                        },
                        new
                        {
                            Id = new Guid("6b47da4e-2e0f-4b4b-8599-8e682394c716"),
                            CreatedAt = new DateTime(2022, 1, 18, 9, 23, 35, 831, DateTimeKind.Utc).AddTicks(1746),
                            Email = "customerone@customer.org",
                            Password = "DQ5nUpGIRAjCb2Sfqa/0/OAPj4saH/+b7QKnTLvDdig=",
                            UpdatedAt = new DateTime(2022, 1, 18, 9, 23, 35, 831, DateTimeKind.Utc).AddTicks(1747),
                            UserType = 1,
                            Username = "customerone"
                        },
                        new
                        {
                            Id = new Guid("3dac46af-aa41-46ff-8c0d-b7f8caf4125d"),
                            CreatedAt = new DateTime(2022, 1, 18, 9, 23, 35, 831, DateTimeKind.Utc).AddTicks(1787),
                            Email = "customertwo@customer.org",
                            Password = "uFAJHMif7jxFxpKpCpyXNiwrf9VJIqGGh/8D7zlJYxI=",
                            UpdatedAt = new DateTime(2022, 1, 18, 9, 23, 35, 831, DateTimeKind.Utc).AddTicks(1787),
                            UserType = 1,
                            Username = "customertwo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
